const players = [
  {
    player_id: "vk_01",
    full_name: "Virat Kohli",
    common_name: "Virat Kohli",
    nationality: "Indian",
    playing_role: "Batsman",
    batting_style: "Right-hand bat",
    bowling_style: "Right-arm medium",
    ipl_teams: ["RCB"],
    is_captain_ever: true,
    ipl_titles_won: 0,
    orange_cap_won: true,
    purple_cap_won: false,
    highest_ipl_score: 113,
    ipl_centuries: 8,
    is_finisher: false,
    is_opener: true,
    is_overseas: false,
    is_currently_active: true,
    is_wicketkeeper: false
  },
  {
    player_id: "msd_02",
    full_name: "Mahendra Singh Dhoni",
    common_name: "MS Dhoni",
    nationality: "Indian",
    playing_role: "Wicketkeeper",
    batting_style: "Right-hand bat",
    bowling_style: "Right-arm medium",
    ipl_teams: ["CSK", "RPS"],
    is_captain_ever: true,
    ipl_titles_won: 5,
    orange_cap_won: false,
    purple_cap_won: false,
    highest_ipl_score: 84,
    ipl_centuries: 0,
    is_finisher: true,
    is_opener: false,
    is_overseas: false,
    is_currently_active: true,
    is_wicketkeeper: true
  },
  {
    player_id: "rs_03",
    full_name: "Rohit Sharma",
    common_name: "Rohit Sharma",
    nationality: "Indian",
    playing_role: "Batsman",
    batting_style: "Right-hand bat",
    bowling_style: "Right-arm offbreak",
    ipl_teams: ["DC", "MI"],
    is_captain_ever: true,
    ipl_titles_won: 6,
    orange_cap_won: false,
    purple_cap_won: false,
    highest_ipl_score: 109,
    ipl_centuries: 2,
    is_finisher: false,
    is_opener: true,
    is_overseas: false,
    is_currently_active: true,
    is_wicketkeeper: false
  },
  {
    player_id: "jb_04",
    full_name: "Jasprit Bumrah",
    common_name: "Jasprit Bumrah",
    nationality: "Indian",
    playing_role: "Bowler",
    batting_style: "Right-hand bat",
    bowling_style: "Right-arm fast",
    ipl_teams: ["MI"],
    is_captain_ever: true,
    ipl_titles_won: 5,
    orange_cap_won: false,
    purple_cap_won: false,
    highest_ipl_score: 16,
    ipl_centuries: 0,
    is_finisher: false,
    is_opener: false,
    is_overseas: false,
    is_currently_active: true,
    is_wicketkeeper: false
  },
  {
    player_id: "abd_05",
    full_name: "AB de Villiers",
    common_name: "AB de Villiers",
    nationality: "South African",
    playing_role: "Batsman",
    batting_style: "Right-hand bat",
    bowling_style: "Right-arm medium",
    ipl_teams: ["DD", "RCB"],
    is_captain_ever: true,
    ipl_titles_won: 0,
    orange_cap_won: false,
    purple_cap_won: false,
    highest_ipl_score: 133,
    ipl_centuries: 3,
    is_finisher: true,
    is_opener: false,
    is_overseas: true,
    is_currently_active: false,
    is_wicketkeeper: true
  },
  {
    player_id: "cg_06",
    full_name: "Chris Gayle",
    common_name: "Chris Gayle",
    nationality: "West Indian",
    playing_role: "Batsman",
    batting_style: "Left-hand bat",
    bowling_style: "Right-arm offbreak",
    ipl_teams: ["KKR", "RCB", "PBKS"],
    is_captain_ever: false,
    ipl_titles_won: 0,
    orange_cap_won: true,
    purple_cap_won: false,
    highest_ipl_score: 175,
    ipl_centuries: 6,
    is_finisher: false,
    is_opener: true,
    is_overseas: true,
    is_currently_active: false,
    is_wicketkeeper: false
  },
  {
    player_id: "lm_07",
    full_name: "Lasith Malinga",
    common_name: "Lasith Malinga",
    nationality: "Sri Lankan",
    playing_role: "Bowler",
    batting_style: "Right-hand bat",
    bowling_style: "Right-arm fast",
    ipl_teams: ["MI"],
    is_captain_ever: false,
    ipl_titles_won: 4,
    orange_cap_won: false,
    purple_cap_won: true,
    highest_ipl_score: 37,
    ipl_centuries: 0,
    is_finisher: false,
    is_opener: false,
    is_overseas: true,
    is_currently_active: false,
    is_wicketkeeper: false
  },
  {
    player_id: "sn_08",
    full_name: "Sunil Narine",
    common_name: "Sunil Narine",
    nationality: "West Indian",
    playing_role: "All-rounder",
    batting_style: "Left-hand bat",
    bowling_style: "Right-arm offbreak",
    ipl_teams: ["KKR"],
    is_captain_ever: false,
    ipl_titles_won: 3,
    orange_cap_won: false,
    purple_cap_won: false,
    highest_ipl_score: 109,
    ipl_centuries: 1,
    is_finisher: false,
    is_opener: true,
    is_overseas: true,
    is_currently_active: true,
    is_wicketkeeper: false
  },
  {
    player_id: "ar_09",
    full_name: "Andre Russell",
    common_name: "Andre Russell",
    nationality: "West Indian",
    playing_role: "All-rounder",
    batting_style: "Right-hand bat",
    bowling_style: "Right-arm fast",
    ipl_teams: ["DD", "KKR"],
    is_captain_ever: false,
    ipl_titles_won: 2,
    orange_cap_won: false,
    purple_cap_won: false,
    highest_ipl_score: 88,
    ipl_centuries: 0,
    is_finisher: true,
    is_opener: false,
    is_overseas: true,
    is_currently_active: true,
    is_wicketkeeper: false
  },
  {
    player_id: "rj_10",
    full_name: "Ravindra Jadeja",
    common_name: "Ravindra Jadeja",
    nationality: "Indian",
    playing_role: "All-rounder",
    batting_style: "Left-hand bat",
    bowling_style: "Slow left-arm orthodox",
    ipl_teams: ["RR", "Kochi", "CSK", "GL"],
    is_captain_ever: true,
    ipl_titles_won: 3,
    orange_cap_won: false,
    purple_cap_won: false,
    highest_ipl_score: 62,
    ipl_centuries: 0,
    is_finisher: true,
    is_opener: false,
    is_overseas: false,
    is_currently_active: true,
    is_wicketkeeper: false
  },
  {
    player_id: "rk_11",
    full_name: "Rashid Khan",
    common_name: "Rashid Khan",
    nationality: "Afghan",
    playing_role: "Bowler",
    batting_style: "Right-hand bat",
    bowling_style: "Legbreak googly",
    ipl_teams: ["SRH", "GT"],
    is_captain_ever: true,
    ipl_titles_won: 1,
    orange_cap_won: false,
    purple_cap_won: false,
    highest_ipl_score: 79,
    ipl_centuries: 0,
    is_finisher: true,
    is_opener: false,
    is_overseas: true,
    is_currently_active: true,
    is_wicketkeeper: false
  },
  {
    player_id: "kl_12",
    full_name: "KL Rahul",
    common_name: "KL Rahul",
    nationality: "Indian",
    playing_role: "Batsman",
    batting_style: "Right-hand bat",
    bowling_style: "None",
    ipl_teams: ["RCB", "SRH", "PBKS", "LSG"],
    is_captain_ever: true,
    ipl_titles_won: 0,
    orange_cap_won: true,
    purple_cap_won: false,
    highest_ipl_score: 132,
    ipl_centuries: 4,
    is_finisher: false,
    is_opener: true,
    is_overseas: false,
    is_currently_active: true,
    is_wicketkeeper: true
  },
  {
    player_id: "rp_13",
    full_name: "Rishabh Pant",
    common_name: "Rishabh Pant",
    nationality: "Indian",
    playing_role: "Wicketkeeper",
    batting_style: "Left-hand bat",
    bowling_style: "None",
    ipl_teams: ["DC"],
    is_captain_ever: true,
    ipl_titles_won: 0,
    orange_cap_won: false,
    purple_cap_won: false,
    highest_ipl_score: 128,
    ipl_centuries: 1,
    is_finisher: true,
    is_opener: false,
    is_overseas: false,
    is_currently_active: true,
    is_wicketkeeper: true
  },
  {
    player_id: "hp_14",
    full_name: "Hardik Pandya",
    common_name: "Hardik Pandya",
    nationality: "Indian",
    playing_role: "All-rounder",
    batting_style: "Right-hand bat",
    bowling_style: "Right-arm fast-medium",
    ipl_teams: ["MI", "GT"],
    is_captain_ever: true,
    ipl_titles_won: 5,
    orange_cap_won: false,
    purple_cap_won: false,
    highest_ipl_score: 91,
    ipl_centuries: 0,
    is_finisher: true,
    is_opener: false,
    is_overseas: false,
    is_currently_active: true,
    is_wicketkeeper: false
  },
  {
    player_id: "yk_15",
    full_name: "Yashasvi Jaiswal",
    common_name: "Yashasvi Jaiswal",
    nationality: "Indian",
    playing_role: "Batsman",
    batting_style: "Left-hand bat",
    bowling_style: "Legbreak",
    ipl_teams: ["RR"],
    is_captain_ever: false,
    ipl_titles_won: 0,
    orange_cap_won: false,
    purple_cap_won: false,
    highest_ipl_score: 124,
    ipl_centuries: 2,
    is_finisher: false,
    is_opener: true,
    is_overseas: false,
    is_currently_active: true,
    is_wicketkeeper: false
  },
  {
  player_id: "as_01",
  full_name: "Abhishek Sharma",
  common_name: "Abhishek Sharma",
  nationality: "Indian",
  playing_role: "Allrounder",
  batting_style: "Left-hand bat",
  bowling_style: "Slow left-arm orthodox",
  ipl_teams: ["DC", "SRH"],
  is_captain_ever: false,
  ipl_titles_won: 1,
  orange_cap_won: false,
  purple_cap_won: false,
  highest_ipl_score: 141,
  ipl_centuries: 1,
  is_finisher: false,
  is_opener: true,
  is_overseas: false,
  is_currently_active: true,
  is_wicketkeeper: false
}
];
